name: message-passing-nn
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.7.6
  - tox=3.14.3
  - numpy=1.17.4
  - pandas=1.0.3
  - pytorch=1.5.0
  - setuptools=46.0.0
  - click